### ISSUE TITLE
RuntimeError: align_to: All input dims must be named.

### ISSUE THREAD

**Issue by ThomasHeap** [alan-ppl/alan_old#6]
https://github.com/alan-ppl/alan/blob/5ef688bc2443f0b0a23ec04219d13b13c65d22be/alan/ml.py#L61

This line will not work if there are "None" dims, as will happen for e.g:

``
self.psi = alan.MLNormal({'plate_ID':I}, sample_shape=(run_type_dim,))
``

Instead we should try getting the names and use align_to?

**Comment by LaurenceA** [comment]
Does it work if you just delete align_as?

**Comment by ThomasHeap** [comment]
> Does it work if you just delete align_as?

That seems to have fixed it.
