### ISSUE TITLE
Defining distributions with scalars but passing list to log prob (Negative Binomial in particular)

### ISSUE THREAD

**Issue by ThomasHeap** [alan-ppl/alan_old#9]
If I want to do something like:

```python
dist = alan.NegativeBinomial(total_count=5, probs=0.5)
samp = [0,1,2,3,4,5]
print(dist.log_prob(samp))
# Expecting output of length 5
```

It will presently throw:

https://github.com/alan-ppl/alan/blob/997a181954f44ea8d437ac9fd80220478c08808c/alan/dist.py#L141

Which seems wrong, perhaps the assert should be changed to:

```python
assert x.ndim == self.result_ndim + self.unnamed_batch_dims  or x.ndim == self.result_ndim + self.unnamed_batch_dims + 1
```

**Comment by LaurenceA** [comment]
try
```
samp = t.tensor([0.,1,2,3,4,5])
```

**Comment by LaurenceA** [comment]
Even that doesn't work, but to me that's expected behaviour.

If you want a valid distribution over 6 things, you need:

dist = alan.NegativeBinomial(total_count=5*t.ones(6), probs=0.5)

samp = t.tensor([0.,1,2,3,4,5])

**Comment by ThomasHeap** [comment]
I'd like it to return a vector of log probabilities the same size as samp. I'm not trying to have a distribution over 6 things I've got 6 samples from a distribution over one thing.

If I do 

```python
dist = alan.NegativeBinomial(total_count=5*t.ones(6), probs=0.5)
samp = t.tensor([0.,1,2,3,4,5])
print(dist.log_prob(samp))
```

It returns a scalar log probability. 

Turning the list to a tensor also doesn't solve the problem either.

**Comment by LaurenceA** [comment]
That's expected behaviour.

If you want a valid distribution over 6 things, you need:

dist = alan.NegativeBinomial(total_count=5*t.ones(6), probs=0.5)

samp = t.tensor([0.,1,2,3,4,5])

Or you can add a torchdim to samp.  And it should be returning a scalar
(which makes things more convenient downstream).

**Comment by ThomasHeap** [comment]
OK well do I have to add a dimension to samp if I want to get a log probability for each of the entries of samp?

**Comment by LaurenceA** [comment]
Yes ... but why is all this such an issue?

**Comment by ThomasHeap** [comment]
Its inconsistent with torch distributions. I think if I have two scalar parameters and I pass a vector of samples of length 6 then I'd expect to get a vector of log probabilities also of length 6.

**Comment by LaurenceA** [comment]
We don't care.  dist.py is not supposed to be used outside Alan.  dist.py
is adapted to make everything downstream in Alan as easy as possible.

**Comment by ThomasHeap** [comment]
Right, ok I'll close this.
